//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoceDetails = new HashSet<InvoceDetail>();
        }
    
        public int id { get; set; }
        public System.DateTime saleDate { get; set; }
        public string invoiceId { get; set; }
        public double totalAfterTax { get; set; }
        public Nullable<int> storeID { get; set; }
        public double tax { get; set; }
        public double totalBefourTax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoceDetail> InvoceDetails { get; set; }
        public virtual Store Store { get; set; }
    }
}
