//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoceDetail
    {
        public int id { get; set; }
        public Nullable<int> invoiceID { get; set; }
        public Nullable<int> itemID { get; set; }
        public Nullable<int> unitID { get; set; }
        public double total { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public double discount { get; set; }
        public double net { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Item Item { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
